substitutions:
  device_name: akvarium_eteto
  device_ip: 192.168.0.147
  board_type: d1_mini

esphome:
  name: ${device_name}
  platform: ESP8266
  board: ${board_type}

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    
  ap:
    ssid: ${device_name}_ssid
  
  # Optional manual IP
  manual_ip:
    static_ip: ${device_ip}
    gateway: !secret network_gateway
    subnet: !secret network_subnet
    dns1: !secret network_dns1
    dns2: !secret network_dns2

logger:

api:
  reboot_timeout: 15min

ota:

web_server:
  port: 80

binary_sensor:
  - platform: status
    name: ${device_name}_status
  - platform: gpio
    pin: 
      number: GPIO12
    name: ${device_name}_stopswitch
    on_press:
      then:
        - switch.turn_off: relay
    internal: true

sensor:
  - platform: uptime
    name: ${device_name}_uptime
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 30s

switch:
  - platform: gpio
    pin: GPIO14
    id: relay
    restore_mode: always_off
  - platform: template
    name: "akvarium_eteto Remote"
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
  - platform: restart
    name: ${device_name}_restart
  - platform: shutdown
    name: ${device_name}_shutdown
  
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip
  - platform: version
    name: ${device_name}_firmware_version
